name: Deploy Website to EC2

on:
  push:
    branches:
      - main  # Deploy on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH key
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        shell: bash

      # Step 3: Add EC2 instance to known hosts
      - name: Add EC2 instance to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts
        shell: bash

      # Step 4: Copy website files to EC2 instance
      - name: Copy files to EC2
        run: |
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r ./path-to-your-website/* ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/var/www/html/
        shell: bash

      # Step 5: Restart web server (optional)
      - name: Restart web server
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} "sudo systemctl restart apache2"
        shell: bash
