name: Deploy to AWS

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    name: Deploy to AWS
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t my-web-app:latest .

      - name: Tag Docker image
        run: |
          docker tag my-web-app:latest my-web-app:latest
          
      - name: Push Docker image
        run: |
          docker push my-web-app:latest
