name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        shell: bash

      - name: Add SSH known hosts
        run: ssh-keyscan -H ec2-52-90-233-81.compute-1.amazonaws.com >> ~/.ssh/known_hosts


      - name: Deploy to AWS
        run: ssh -i ~/.ssh/id_rsa ubuntu@ec2-<52.90.233.81>.compute.amazonaws.com 
