name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        shell: bash

      - name: Add EC2 to known hosts
        run: |
          ssh-keyscan -H 52.90.233.81 >> ~/.ssh/known_hosts
        shell: bash

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@52.90.233.81 << 'EOF'
            cd /path/to/your/project
            git pull origin main
            npm install
            npm run build
            # Add other deployment commands here
          EOF
        shell: bash
