name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Host *" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
        shell: bash

      - name: Add SSH known hosts
        run: |
          ssh-keyscan -H 52.90.233.81 >> ~/.ssh/known_hosts
        shell: bash

      - name: Deploy to EC2
        run: |
          ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@52.90.233.81 << 'EOF'
          # Your deployment command goes here
          echo "Deploying to EC2"
          EOF
        shell: bash
